version: '3'
services:
  nginx:
    image: nginx:1.11
    ports: 
      - 81:80   
    volumes:
      - ./static/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/data/static/
    networks:
      - customNetwork
  apache:
    image: php:7.4-apache
    build: ./dynamic
    ports: 
      - 82:80 
    volumes:
      - ./dynamic:/var/www/html/
      - ./dynamic/000-default.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - my-sql
    environment:
      - DB_HOST=my-sql
      - DB_PORT=3306
      - DB_NAME=coffeeworld
      - DB_USER=user
      - DB_PASSWORD=password
    networks:
      - customNetwork
  my-sql:
    image: mysql:latest
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_volume:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: password
    networks:
      - customNetwork
    
volumes:
  db_volume:
  
networks:
  customNetwork: