version: '3'
services:
  db:
    image: mysql
    restart: always
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: mysqld --init-file="/docker-entrypoint-initdb.d/init.sql"
    environment: 
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3308:3306"
  nginx:
    image: nginx:1.11
    restart: always 
    volumes:
      - ./nginx/src:/var/www/html/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports: 
      - 81:80  
  apache:
    build: ./apache
    restart: always
    ports: 
      - 82:80 
    volumes:
      - ./apache/src:/var/www/html/
      - ./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports: 
      - 82:80
  
